version: '3'

services:
  twitch_bot:
    build: 
      context: ./
      dockerfile: ./twitch/dockerfile
    container_name: twitch_bot
    restart: unless-stopped
    volumes:
      - /mnt/disk1/JangBot/data:/data
  discord_bot:
    build: 
      context: ./
      dockerfile: ./discord/dockerfile
    container_name: discord_bot
    restart: unless-stopped
    volumes:
      - /mnt/disk1/JangBot/data:/data

