version: '3'

services:
  twitch_bot:
    build: 
      context: ./
      dockerfile: ./twitch/dockerfile
    container_name: twitch_bot
    restart: unless-stopped
    volumes:
      - ty/mnt/disk1/JangBot/data/dailyCoinUserDates.json:/data/dailyCoinUserDates.json
      - /mnt/disk1/JangBot/data/jinnCoinUserStore.json:/data/jinnCoinUserStore.json
      - /mnt/disk1/JangBot/data/program_data.json:/data/program_data.json
  discord_bot:
    build: 
      context: ./
      dockerfile: ./discord/dockerfile
    container_name: discord_bot
    restart: unless-stopped
    volumes:
      - type: bind
        source: ty/mnt/disk1/JangBot/data/dailyCoinUserDates.json
        target: /data/dailyCoinUserDates.json
      - type: bind
        source: /mnt/disk1/JangBot/data/jinnCoinUserStore.json
        target: /data/jinnCoinUserStore.json
      - type: bind
        source: /mnt/disk1/JangBot/data/program_data.json
        target: /data/program_data.json

